# fly.toml app configuration file generated for nuxt-salads-demo on 2023-09-01T14:51:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nuxt-salads-demo"
primary_region = "ams"

[build]

[env]
  API_URL = "https://dorianm.com/nuxt-recipes-api"
  CDN_URL = "https://dorianm.com/nuxt-recipes-images"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
